name: Release Artifacts
on:
  push:
    branches: [ master, 'stable/*' ]
  pull_request:
    branches: [ master, 'stable/*' ]
jobs:
  wheel-build:
    name: Build and Publish Release Artifacts
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'
      - name: Install Deps
        run: pip install -U twine
      - name: Build Artifacts
        run: python3 setup.py sdist bdist_wheel
#      - name: Publish to PyPi
#       env:
#          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
#          TWINE_USERNAME: qiskit
#        run: twine upload dist/qiskit*
